name = "carbonledger-api"
main = "index.ts"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "carbonledger"
database_id = "your-database-id"

[[routes]]
pattern = "api.carbonledger.com"
custom_domain = true

[env.preview]
name = "carbonledger-api-preview"
[env.preview.vars]
ENVIRONMENT = "preview"

# Enable the Workers DevTools
[dev]
port = 8787
local_protocol = "http" 
